#################################################################################
##___________________________  _____  ____   ____  ____________________________##
##___________________________ |_   _|/ ___| / ___| ____________________________##
##___________________________   | | | |  _ | |     ____________________________##
##___________________________   | | | |_| || |___  ____________________________##
##___________________________   |_|  \____| \____| ____________________________##
##                             TheGentleChallenges                             ##
##                                Configuration                                ##
##                                                                             ##
##   WEBSITE:       https://marcpg.com/                                        ##
##   SOURCE-CODE:   https://github.com/MarcPG1905/TheGentleChallenges          ##
##   BUGS & ISSUES: https://github.com/MarcPG1905/TheGentleChallenges/issues   ##
##                                                                             ##
#################################################################################


## If teams are randomized. ##
random-teams: false

## A list of players for each team. ##
# This only does something if "random-teams" above is set to false.
teams:
  - [ "Example1", "Example2" ]
  - [ "SomeExample", "YetAnotherExampleUser", "WowAThirdUserInTeam" ]
  - [ "SomeUserForTeam3", "AnotherOne" ]


## The aggressive mobs challenge. ##
# The keys should be the same as the ones also used in commands.
# The values are the damage. 2.0 Damage = 1 Heart
aggressive-mobs:
  cat: 5.5
  cow: 5.0
  donkey: 2.5
  fox: 3.5
  glow_squid: 3.2
  horse: 4.2
  mooshroom: 3.8
  mule: 3.0
  ocelot: 6.0
  pig: 3.5
  sheep: 2.5
  skeleton_horse: 3.5
  squid: 3.2
  turtle: 4.0
  villager: 5.2
  wandering_trader: 5.0


## The monster army battles. ##
monster-army-battle:

  # How the item randomizer is seperated.
  #  Available:
  #    | -> global  : everyone has the same
  #    | -> team    : each team has their own
  #    | -> player  : each player has their own
  randomizer-mode: team

  # How/when players respawn if they died in battle.
  #  Available:
  #    | -> round   : after each round/wave
  #    | -> time    : after a specified amount of time passed
  respawn-mode: round

  # The time that has to pass before a player respawns.
  # This only does something if "respawn-mode" above is set to "time".
  respawn-time: 0

  # How long the collection time lasts.
  # This is specified in seconds.
  collection-time-seconds: 3600

  # The location inside the battle arena where players will spawn.
  arena-spawn: [ -44, 71, 104 ]

  # Points of a polygon defying the monster spawn area.
  arena-bounds:
    - [ 10, 55 ]
    - [ -35, 55 ]
    - [ -75, 95 ]
    - [ -75, 115 ]
    - [ -35, 155 ]
    - [ 10, 155 ]
    - [ 45, 115 ]
    - [ 45, 90 ]
