#################################################################################
##___________________________  _____  ____   ____  ____________________________##
##___________________________ |_   _|/ ___| / ___| ____________________________##
##___________________________   | | | |  _ | |     ____________________________##
##___________________________   | | | |_| || |___  ____________________________##
##___________________________   |_|  \____| \____| ____________________________##
##                             TheGentleChallenges                             ##
##                                Configuration                                ##
##                                                                             ##
##   WEBSITE:       https://marcpg.com/                                        ##
##   SOURCE-CODE:   https://github.com/MarcPG1905/TheGentleChallenges          ##
##   BUGS & ISSUES: https://github.com/MarcPG1905/TheGentleChallenges/issues   ##
##                                                                             ##
#################################################################################


## If teams are randomized. ##
random-teams: false

## A list of players for each team. ##
# This only does something if "random-teams" above is set to false.
teams:
  - [ "Example1", "Example2" ]
  - [ "SomeExample", "YetAnotherExampleUser", "WowAThirdUserInTeam" ]
  - [ "SomeUserForTeam3", "AnotherOne" ]


## The random worlds challenge. ##
random-worlds:

  # The minimum time in seconds between each world change.
  interval-min: 300 # 300s = 5min

  # The maximum time in seconds between each world change.
  interval-max: 600 # 600s = 10min

  # The maximum time in seconds in each world.
  max-world-time: 300 # 300s = 5min

  # If the inventory is cleared whilst in a random world.
  clear-inv: true

  # The worlds that are available.
  worlds:
    - name: world_name
      spawn: [ 0, 0, 0 ]
      title: Some World
      creator: Cool Name
    - name: another_world
      spawn: [ 10, 20, 30 ]
      title: Another World
      creator: Player123


## The Hide n' Seek game. ##
hide-n-seek:

  # The seeker's username. If this player is not online, a random player will be chosen.
  seeker: Player123

  # The spawn inside the Hide n' Seek map.
  spawn: [ 0, 0, 0 ]

  # The time in seconds that players can hide until the seeker can start searching.
  hiding-time: 300 # 600s = 10min

  # The maximum time in seconds the hide n' seek will go.
  total-time: 3600 # 3600s = 1h

  # The time in seconds until hints start appearing.
  hint-time: 2700 # 2700s = 45min

  # The time in seconds between each hint.
  hint-interval: 30

  # How the hints work after the "hint-time" has passed.
  #  Available:
  #    | -> none  : nothing will happen
  #    | -> glow  : all players glow for a few seconds
  #    | -> sound : all players play a sound
  hint-type: glow


## The aggressive mobs challenge. ##
# The keys should be the same as the ones also used in commands.
# The values are the damage. 2.0 Damage = 1 Heart
aggressive-mobs:
  cat: 5.5
  cow: 5.0
  donkey: 2.5
  fox: 3.5
  glow_squid: 3.2
  horse: 4.2
  mooshroom: 3.8
  mule: 3.0
  ocelot: 6.0
  pig: 3.5
  sheep: 2.5
  skeleton_horse: 3.5
  squid: 3.2
  turtle: 4.0
  villager: 5.2
  wandering_trader: 5.0


## The monster army battles. ##
monster-army-battle:

  # How the item randomizer is seperated.
  #  Available:
  #    | -> global  : everyone has the same
  #    | -> team    : each team has their own
  #    | -> player  : each player has their own
  randomizer-mode: team

  # How/when players respawn if they died in battle.
  #  Available:
  #    | -> round   : after each round/wave
  #    | -> time    : after a specified amount of time passed
  respawn-mode: round

  # The time that has to pass before a player respawns.
  # This only does something if "respawn-mode" above is set to "time".
  respawn-time: 0

  # How long the collection time lasts.
  # This is specified in seconds.
  collection-time-seconds: 3600

  # The location inside the battle arena where players will spawn.
  arena-spawn: [ -44, 71, 104 ]

  # Points of a polygon defying the monster spawn area.
  arena-bounds:
    - [ 10, 55 ]
    - [ -35, 55 ]
    - [ -75, 95 ]
    - [ -75, 115 ]
    - [ -35, 155 ]
    - [ 10, 155 ]
    - [ 45, 115 ]
    - [ 45, 90 ]
